language: node_js
node_js:
- '10.10'
deploy:
  provider: heroku
  app: cs-solex-bot
  api_key:
    secure: q6hO16UOp4X529Xhvh/IAElGb7N82sDoeDySjxI3lUr+bjyeLKOo6V0oyHQV+Y8FWADjwo7/3U1OxGxCAJzMkUwvHSGjyTctfySiX5CO5A7W0egxjv721zh7vzanILB/WIgds3YX1/Z5jpQriALtZyFcA7uY/BWpygidTwKPNkrazfwXb/Mzxv5r9JHvyOEvfOas5p9PzADiLDhsu1vlX6zznLiomdZnMDoLPzuE9vIXkyckhRTwBotY2lsw2qtxSJww7eU9DDbWIcXokn8H+7i/92VbOBCi/Z82Od5aF5W5kEd6hZh0CMup9ocZdKuh2Rr5YPqnm7eY9nKw7Lus/toGmJEPbcxw5tfbyujQnhf1ertcyX5Zlr/4PhTtBL7uyGpnV01HlpNvkiey5CYszuUS4qPcauQgBNsxthJG3T1DAu+terPbe1ofmlv8SixnIrkUQpMea57axqhmq3b8Z9mHYoNcfNmUuPRGOMH10tsvRncAGNFEgE92iGz0PemZE1lHeue0awZHTlGAuB4FoMJGXDjAaaCxE6D0pvvAd4rXuxondGA9fUEivWPi1pDoSzIMLanO1kpNhnx4Bt81hMHUB3eaMUktAsnfNx9nic9tqjbapZVCi15uQHvOxORuBtLtJiHJYGPkF7JwQNI36dE1sC+eDUxPH1RP+EuRnvE=
